# Deploy website via nginx
FROM nginx:stable
MAINTAINER Wayne Shelley

# Set environment vars
ENV BASE_URL /
ENV API_HOST https://epos.cineca.it/

# Copy from website dist from build container
COPY dist /opt/epos-gui/

# Copy nginx config from build container
COPY nginx-config/nginx-docker-sites-enabled-default /etc/nginx/conf.d/default.conf

# Starting directory
WORKDIR /opt/epos-gui/

# Fix base url paths
CMD sed -i 's|<base href="/">|<base href="'$BASE_URL'">|g' /opt/epos-gui/index.html && \
    sed -i 's|^\(\s*\)rewrite ^/(.*)$ /$1 last;|\1rewrite ^'$BASE_URL'(.*)$ /$1 last;|g' /etc/nginx/conf.d/default.conf && \
    sed -i 's|https://epos.cineca.it/|'$API_HOST'|g' /etc/nginx/conf.d/default.conf && \
    nginx -g "daemon off;"

EXPOSE 80
